version: '3.4'

networks:
  frontend:
  backend:


services:
  eventscatalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventsDb
      DatabaseUser: sa
      DatabasePassword: EventsAPI!
      ExternalCatalogUrl: http://localhost:7001
    ports:
      - "7001:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver    

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventsCatalogUrl: http://eventscatalog
      IdentityUrl: http://192.168.0.214:7800
      CallBackUrl: http://localhost:7025
    ports:
      - "7025:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - eventscatalog
      - tokenserver

  tokenserver:
    image: events/tokenapi
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://webmvc
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokensqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: EventsAPI!
    ports:
      - "1500:1433"
    container_name: eventssqlserver
    networks:
      - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: EventsAPI!
    ports:
      - "1449:1433"
    container_name: eventstokensqlserver
    networks:
      - backend